
# Отключить/включить проверку авторизации (для тестов)
app.auth.disabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/tictactoe_db
spring.datasource.username=ttt_user
spring.datasource.password=ndeb43n245
spring.datasource.driver-class-name=org.postgresql.Driver

# ????? Hibernate ??? ???????? ??????? ?? ?????? ????? ??????? (User, GameLog)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ????????? ????????? ???? ?????? ? ??????????? ?????? (H2)
# spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
# ????? ????? ???? ????? ? ?????????? ???? ????? ??????? (???????????)
#spring.h2.console.enabled=true
